package com.baoverung.app.data.local

import androidx.room.*
import com.baoverung.app.data.local.entity.*
import kotlinx.coroutines.flow.Flow

@Database(
    entities = [
        WaypointEntity::class,
        TrackLogEntity::class,
        PatrolLogEntity::class,
        DailyJournalEntity::class,
        GisLayerEntity::class,
        FloraFaunaLogEntity::class,
        NaturalImpactLogEntity::class,
        PolygonEntity::class
    ],
    version = 1,
    exportSchema = false
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun waypointDao(): WaypointDao
    abstract fun trackLogDao(): TrackLogDao
    abstract fun patrolLogDao(): PatrolLogDao
    abstract fun dailyJournalDao(): DailyJournalDao
    abstract fun gisLayerDao(): GisLayerDao
    abstract fun floraFaunaLogDao(): FloraFaunaLogDao
    abstract fun naturalImpactLogDao(): NaturalImpactLogDao
    abstract fun polygonDao(): PolygonDao
}

/**
 * Interface required by Room to instantiate the database.
 * The implementation is generated by KSP.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase>

@Dao
interface WaypointDao {
    @Query("SELECT * FROM waypoints ORDER BY timestampUtc DESC")
    fun getAllWaypoints(): Flow<List<WaypointEntity>>
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(waypoint: WaypointEntity)
    
    @Delete
    suspend fun delete(waypoint: WaypointEntity)

    @Query("SELECT * FROM waypoints WHERE id = :id")
    suspend fun getById(id: Long): WaypointEntity?
}

@Dao
interface TrackLogDao {
    @Query("SELECT * FROM track_logs ORDER BY startTimeUtc DESC")
    fun getAllTrackLogs(): Flow<List<TrackLogEntity>>
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(track: TrackLogEntity)
    
    @Delete
    suspend fun delete(track: TrackLogEntity)
}

@Dao
interface PatrolLogDao {
    @Query("SELECT * FROM patrol_logs ORDER BY discoveryTimeUtc DESC")
    fun getAllPatrolLogs(): Flow<List<PatrolLogEntity>>
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(patrol: PatrolLogEntity)
    
    @Delete
    suspend fun delete(patrol: PatrolLogEntity)

    @Query("SELECT * FROM patrol_logs WHERE id = :id")
    suspend fun getById(id: Long): PatrolLogEntity?
}

@Dao
interface DailyJournalDao {
    @Query("SELECT * FROM daily_journals ORDER BY timestampUtc DESC")
    fun getAllDailyJournals(): Flow<List<DailyJournalEntity>>
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(journal: DailyJournalEntity)
    
    @Delete
    suspend fun delete(journal: DailyJournalEntity)

    @Query("SELECT * FROM daily_journals WHERE id = :id")
    suspend fun getById(id: Long): DailyJournalEntity?
}

@Dao
interface GisLayerDao {
    @Query("SELECT * FROM gis_layers ORDER BY priority ASC")
    fun getAllGisLayers(): Flow<List<GisLayerEntity>>
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(layer: GisLayerEntity)
    
    @Delete
    suspend fun delete(layer: GisLayerEntity)
}

@Dao
interface FloraFaunaLogDao {
    @Query("SELECT * FROM flora_fauna_logs ORDER BY timestampUtc DESC")
    fun getAllLogs(): Flow<List<FloraFaunaLogEntity>>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(log: FloraFaunaLogEntity)

    @Delete
    suspend fun delete(log: FloraFaunaLogEntity)

    @Query("SELECT * FROM flora_fauna_logs WHERE id = :id")
    suspend fun getById(id: Long): FloraFaunaLogEntity?
}

@Dao
interface NaturalImpactLogDao {
    @Query("SELECT * FROM natural_impact_logs ORDER BY timestampUtc DESC")
    fun getAllLogs(): Flow<List<NaturalImpactLogEntity>>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(log: NaturalImpactLogEntity)

    @Delete
    suspend fun delete(log: NaturalImpactLogEntity)

    @Query("SELECT * FROM natural_impact_logs WHERE id = :id")
    suspend fun getById(id: Long): NaturalImpactLogEntity?
}

@Dao
interface PolygonDao {
    @Query("SELECT * FROM polygons ORDER BY timestampUtc DESC")
    fun getAllPolygons(): Flow<List<PolygonEntity>>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(polygon: PolygonEntity)

    @Delete
    suspend fun delete(polygon: PolygonEntity)
}
