package com.baoverung.app.data.local

import androidx.room.*
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import com.baoverung.app.data.local.entity.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO
import kotlinx.coroutines.flow.Flow

@Database(
    entities = [
        WaypointEntity::class,
        TrackLogEntity::class,
        PatrolLogEntity::class,
        DailyJournalEntity::class,
        GisLayerEntity::class
    ],
    version = 1,
    exportSchema = false
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun waypointDao(): WaypointDao
    abstract fun trackLogDao(): TrackLogDao
    abstract fun patrolLogDao(): PatrolLogDao
    abstract fun dailyJournalDao(): DailyJournalDao
    abstract fun gisLayerDao(): GisLayerDao
}

/**
 * Interface required by Room to instantiate the database.
 * The implementation is generated by KSP.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase>

@Dao
interface WaypointDao {
    @Query("SELECT * FROM waypoints ORDER BY timestampUtc DESC")
    fun getAllWaypoints(): Flow<List<WaypointEntity>>
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(waypoint: WaypointEntity)
    
    @Delete
    suspend fun delete(waypoint: WaypointEntity)
}

@Dao
interface TrackLogDao {
    @Query("SELECT * FROM track_logs ORDER BY startTimeUtc DESC")
    fun getAllTrackLogs(): Flow<List<TrackLogEntity>>
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(track: TrackLogEntity)
    
    @Delete
    suspend fun delete(track: TrackLogEntity)
}

@Dao
interface PatrolLogDao {
    @Query("SELECT * FROM patrol_logs ORDER BY discoveryTimeUtc DESC")
    fun getAllPatrolLogs(): Flow<List<PatrolLogEntity>>
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(patrol: PatrolLogEntity)
    
    @Delete
    suspend fun delete(patrol: PatrolLogEntity)
}

@Dao
interface DailyJournalDao {
    @Query("SELECT * FROM daily_journals ORDER BY timestampUtc DESC")
    fun getAllDailyJournals(): Flow<List<DailyJournalEntity>>
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(journal: DailyJournalEntity)
    
    @Delete
    suspend fun delete(journal: DailyJournalEntity)
}

@Dao
interface GisLayerDao {
    @Query("SELECT * FROM gis_layers ORDER BY priority ASC")
    fun getAllGisLayers(): Flow<List<GisLayerEntity>>
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(layer: GisLayerEntity)
    
    @Delete
    suspend fun delete(layer: GisLayerEntity)
}

fun getAppDatabase(
    builder: RoomDatabase.Builder<AppDatabase>
): AppDatabase {
    return builder
        .setDriver(BundledSQLiteDriver())
        .setQueryCoroutineContext(Dispatchers.IO)
        .fallbackToDestructiveMigration(true)
        .build()
}
